create DATABASE WIIE_database

IF OBJECT_ID('WIDE', 'U') IS NOT NULL
	DROP TABLE WIDE
CREATE TABLE WIDE(
	iso_code VARCHAR(10),
	region_group VARCHAR(50),
	income_group VARCHAR(50),
	country VARCHAR(50),
	survey VARCHAR(10),
	[year] DATE,
	category VARCHAR(50),
	sex varchar(10),
	[location] VARCHAR(10),
	wealth VARCHAR(10),
	comp_prim_v2_m FLOAT,
	comp_lowsec_v2_m FLOAT,
	comp_upsec_v2_m FLOAT,
	comp_prim_1524_m FLOAT,
	comp_lowsec_1524_m FLOAT,
	comp_upsec_2029_m FLOAT,
	eduyears_2024_m FLOAT,
	edu2_2024_m FLOAT,
	edu4_2024_m FLOAT,
	eduout_prim_m FLOAT,
	eduout_lowsec_m FLOAT,
	eduout_upsec_m FLOAT,
	comp_prim_v2_no INT,
	comp_lowsec_v2_no INT,
	comp_upsec_v2_no INT,
	comp_prim_1524_no INT,
	comp_lowsec_1524_no INT,
	comp_upsec_2029_no INT,
	eduyears_2024_no INT,
	edu2_2024_no INT,
	edu4_2024_no INT,
	eduout_prim_no INT,
	eduout_lowsec_no INT,
	eduout_upsec_no INT,
	edu0_prim_m FLOAT,
	edu0_prim_no INT,
	trans_prim_m FLOAT,
	trans_prim_no INT,
	trans_lowsec_m FLOAT,
	trans_lowsec_no INT,
	comp_higher_2yrs_2529_m FLOAT,
	comp_higher_2yrs_2529_no INT,
	comp_higher_4yrs_2529_m FLOAT,
	comp_higher_4yrs_2529_no INT,
	comp_higher_4yrs_3034_m FLOAT,
	comp_higher_4yrs_3034_no INT,
	attend_higher_1822_m FLOAT,
	attend_higher_1822_no INT,
	overage2plus_m FLOAT,
	overage2plus_no INT,
	literacy_1524_m FLOAT,
	literacy_1524_no INT,
	mlevel1_m FLOAT,
	mlevel1_no INT,
	rlevel1_m FLOAT,
	rlevel1_no INT,
	slevel1_m FLOAT,
	slevel1_no INT,
	mlevel2_m FLOAT,
	mlevel2_no INT,
	rlevel2_m FLOAT,
	rlevel2_no INT,
	slevel2_m FLOAT,
	slevel2_no INT,
	mlevel3_m FLOAT,
	mlevel3_no INT,
	rlevel3_m FLOAT,
	rlevel3_no INT,
	slevel3_m FLOAT,
	slevel3_no INT,
	mlevel4_m FLOAT,
	mlevel4_no INT,
	rlevel4_m FLOAT,
	rlevel4_no INT,
	slevel4_m FLOAT,
	slevel4_no INT
)

BULK INSERT WIDE
FROM 'C:\Users\oussama\Desktop\PFF\generated_data\WIDE_clean.csv'
WITH(
	FORMAT = 'CSV',
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
)

SELECT * FROM WIDE